name: Python CICD

on:
  pull_request:
    branches: [ main, develop ]

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run pre-commit hooks
            uses: pre-commit/action@v3.0.1
            with:
              extra_args: --all-files --config pre_commit.yml
            continue-on-error: true

    pytest:
        runs-on: ubuntu-latest
        needs: pre-commit

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v0.5.0
              with:
                credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

            - name: Run tests
              run: |
                pytest tests/

    deploy:
      runs-on: ubuntu-latest
      needs: pytest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up gcloud CLI
          uses: google-github-actions/auth@v2
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: Configure Google Cloud project
          run: gcloud config set project lolffate

        - name: Configure Docker for GCR
          run: gcloud auth configure-docker

        - name: Build Docker image
          run: docker build -f src/online_app/Dockerfile -t gcr.io/lolffate/flask-app:$GITHUB_SHA src/online_app


        - name: Push Docker image
          run: docker push gcr.io/lolffate/flask-app:$GITHUB_SHA

        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy flask-app \
              --image gcr.io/lolffate/flask-app:$GITHUB_SHA \
              --region europe-west1 \
              --platform managed \
              --allow-unauthenticated
